export const techCompanies = [
  {
    name: "a",
    company: [
      {
        companyName: "Abeg",
        companyTwitterHandle: "abeg_app",
        foundersTwitterHandle: ["dare___a"],
        industry: "FinTech",
        website: "https://abeg.app/",
      },
      {
        companyName: "Acadar",
        companyTwitterHandle: "Acadar",
        foundersTwitterHandle: ["OnyimeStan"],
        industry: "EduTech",
        website: "https://acadar.com",
      },
      {
        companyName: "Ace",
        companyTwitterHandle: "Ace",
        foundersTwitterHandle: ["ercineksin", "tundekehinde"],
        industry: "Logistics",
        website: "https://www.ace.ng",
      },
      {
        companyName: "Africas Talking",
        companyTwitterHandle: "Africastalking",
        foundersTwitterHandle: ["sgikandi"],
        industry: "Mobile Communications Solutions",
        website: "https://africastalking.com",
      },
      {
        companyName: "Afriktrip",
        companyTwitterHandle: "afriktrip",
        foundersTwitterHandle: ["mr_adesal"],
        industry: "Travels and Tours",
        website: "https://afriktrip.com",
      },
      {
        companyName: "An African Future",
        companyTwitterHandle: "anafricanfuture",
        foundersTwitterHandle: ["iaboyeji"],
        industry: "VC",
        website: "https://www.future.africa",
      },
      {
        companyName: "AltSchool Africa",
        companyTwitterHandle: "AltSchoolAfrica",
        foundersTwitterHandle: ["AdewaleYusuf_", "hackSultan"],
        industry: "EduTech",
        website: "https://altschoolafrica.com",
      },
      {
        companyName: "Autochek Africa",
        companyTwitterHandle: "AutochekAfrica",
        foundersTwitterHandle: ["etopty"],
        industry: "Automobile/AutoTech",
        website: "https://www.autochek.africa/ng",
      },
    ],
  },
  {
    name: "b",
    company: [
      {
        companyName: "BanklyNG",
        companyTwitterHandle: "BanklyNG",
        foundersTwitterHandle: [],
        industry: "Digital Wealth (FinTech)",
        website: "https://www.bankly.ng",
      },
      {
        companyName: "Brass",
        companyTwitterHandle: "brassbanking",
        foundersTwitterHandle: ["akindolu"],
        industry: "Business Banking",
        website: "https://www.trybrass.com",
      },
      {
        companyName: "Bridger Africa",
        companyTwitterHandle: "Bridgerafrica",
        foundersTwitterHandle: ["JSBabasanmi"],
        industry: "Export and Export financing",
        website: "http://app.bridger.africa",
      },
      {
        companyName: "Build with Bloc",
        companyTwitterHandle: "buildwithbloc",
        foundersTwitterHandle: ["pyjama_ceo"],
        industry: "FinTech",
        website: "https://www.blochq.io",
      },
      {
        companyName: "Bukableco",
        companyTwitterHandle: "bukableco",
        foundersTwitterHandle: ["enyosam_"],
        industry: "Freelance, Tech learning & Outsourcing",
        website: "https://www.bukable.co",
      },
      {
        companyName: "Buy Safe House",
        companyTwitterHandle: "buysafehouse",
        foundersTwitterHandle: ["SeunKOlajide"],
        industry: "Real Estate",
        website: "https://www.buysafehouse.com",
      },
    ],
  },
  {
    name: "c",
    company: [
      {
        companyName: "Cellulant",
        companyTwitterHandle: "Cellulant",
        foundersTwitterHandle: ["KenNjorogeCG", "BolajiAkinboro"],
        industry: "Financial Services",
        website: "https://cellulant.io",
      },
      {
        companyName: "CHAfrica Tech",
        companyTwitterHandle: "CHAfrica_Tech",
        foundersTwitterHandle: ["chizom_"],
        industry: "EduTech",
        website:
          "https://flutterwave.com/store/codehub?_ga=2.169721825.1570256633.1634980577-89854525.1630514755",
      },
      {
        companyName: "Cowrywise",
        companyTwitterHandle: "Cowrywise",
        foundersTwitterHandle: [],
        industry: "Digital Wealth (FinTech)",
        website: "https://cowrywise.com",
      },
      {
        companyName: "Craft SiliconKE",
        companyTwitterHandle: "CraftSiliconKE",
        foundersTwitterHandle: ["KBudhabhatti"],
        industry: "Financial Services",
        website: "https://www.craftsilicon.com",
      },
    ],
  },
  {
    name: "d",
    company: [
      {
        companyName: "DarumNg",
        companyTwitterHandle: "DarumNg",
        foundersTwitterHandle: [],
        industry: "Logistics",
        website: "https://darum.ng",
      },
      {
        companyName: "Decagon",
        companyTwitterHandle: "DecagonIns",
        foundersTwitterHandle: ["ChikaNwobi"],
        industry: "Tech learning & outsourcing",
        website: "https://decagonhq.com",
      },
      {
        companyName: "Devdex Software",
        companyTwitterHandle: "devdex_software",
        foundersTwitterHandle: ["NanaOBosompem"],
        industry: "Health",
        website: "https://devdexsoftware.com",
      },
    ],
  },
  {
    name: "e",
    company: [
      {
        companyName: "ecoSokoni",
        companyTwitterHandle: "ecoSokoni",
        foundersTwitterHandle: ["MHANDISI_IAN"],
        industry: "AgroTech",
        website: "https://www.ecosokoni.co.ke",
      },
      {
        companyName: "EGMarkets",
        companyTwitterHandle: "EGMarkets",
        foundersTwitterHandle: [],
        industry: "Financial Derivatives",
        website: "http://access.eagleglobalmarkets.com",
      },
      {
        companyName: "Ejara",
        companyTwitterHandle: "EjaraApp",
        foundersTwitterHandle: ["chakaneld"],
        industry: "FinTech",
        Wwbsite: "https://www.ejara.io",
      },
      {
        companyName: "ErrandLr",
        companyTwitterHandle: "ErrandLr",
        foundersTwitterHandle: ["jide_tade"],
        industry: "Logistics",
        website: "https://errandlr.com",
      },
    ],
  },
  {
    name: "f",
    company: [
      {
        companyName: "Famasi Africa",
        companyTwitterHandle: "FamasiAfrica",
        foundersTwitterHandle: ["justsay_didi", "alfaruqstories"],
        industry: "Digital pharmacy",
        website: "https://www.famasi.africa/plans-and-pricing",
      },
      {
        companyName: "Farmed NG",
        companyTwitterHandle: "Farmed_NG",
        foundersTwitterHandle: ["jay_can_do", "27kJamal", "edidiongmekong"],
        industry: "AgroTech",
        website: "https://facebook.com/FarmedForte",
      },
      {
        companyName: "FirstCheck",
        companyTwitterHandle: "FirstCheckHQ",
        foundersTwitterHandle: ["ElohoGM", "OdunEweniyi"],
        industry: "VC",
        website: "https://www.firstcheck.africa",
      },
      {
        companyName: "Flutterwave",
        companyTwitterHandle: "Theflutterwave",
        foundersTwitterHandle: ["TechProd_Arch", "iaboyeji"],
        industry: "Payment infrastructure",
        website: "https://www.flutterwave.com/us",
      },
      {
        companyName: "FlyingDoctorsIC",
        companyTwitterHandle: "FlyingDoctorsIC",
        foundersTwitterHandle: ["NaijaFlyingDr"],
        industry: "HealthCare",
        website: "http://fdinvestmentcompany.com",
      },
      {
        companyName: "FluxTech Africa",
        companyTwitterHandle: "FluxTechAfrica",
        foundersTwitterHandle: ["isokowalter"],
        industry: "Tech Consulting + Software Services",
        website: "https://fluxtechafrica.com",
      },
      {
        companyName: "FourthCanvas",
        companyTwitterHandle: "FourthCanvas",
        foundersTwitterHandle: ["victorfatanmi"],
        industry: "PR/Marketing/Brand strategy",
        website: "https://africachallengerbrands.com",
      },
      {
        companyName: "Frain Dev",
        companyTwitterHandle: "frainDev",
        foundersTwitterHandle: ["subomiOluwalana", "emmanuelaina_"],
        industry: "Developer Tools",
        website: "https://frain.dev",
      },
    ],
  },
  {
    name: "g",
    company: [
      {
        companyName: "Geotopup",
        companyTwitterHandle: "Geotopup",
        foundersTwitterHandle: ["ejilolahmed"],
        industry: "Fintech",
        website: "https://geotopup.com",
      },
      {
        companyName: "getBumpa",
        companyTwitterHandle: "getBumpa",
        foundersTwitterHandle: ["tushgeek", "TeeJaY_Codes"],
        industry: "E-commerce Founders",
        website: "https://getbumpa.com",
      },
      {
        companyName: "getdisha",
        companyTwitterHandle: "getdisha",
        foundersTwitterHandle: ["evansakanno"],
        industry: "Media",
        website: "https://disha.page",
      },
      {
        companyName: "getequity",
        companyTwitterHandle: "getequity",
        foundersTwitterHandle: ["bigbrutha_", "WilliamOkafor"],
        industry: "Startup Financing",
        website: "https://www.getequity.io",
      },
      {
        companyName: "grazacng",
        companyTwitterHandle: "grazacng",
        foundersTwitterHandle: ["AdeleyeVictor_"],
        industry: "Tech Education",
        website: "https://www.grazac.com.ng",
      },
      {
        companyName: "Grey",
        companyTwitterHandle: "Grey",
        foundersTwitterHandle: ["femicodes", "kingidee"],
        industry: "FinTech",
        website: "https://grey.co",
      },
    ],
  },
  {
    name: "h",
    company: [
      {
        companyName: "Halotechafrica",
        companyTwitterHandle: "Halotechafrica",
        foundersTwitterHandle: ["robertyenji"],
        industry: "Software Services",
        website: "https://www.halotechafrica.com",
      },
      {
        companyName: "handypal_ng",
        companyTwitterHandle: "handypal_ng",
        foundersTwitterHandle: ["alajabrownedola"],
        industry: "ArtisanTech",
        website: "http://www.hanypalng.com",
      },
      {
        companyName: "HerconomybyAGS",
        companyTwitterHandle: "HerconomybyAGS",
        foundersTwitterHandle: ["ifedurosinmiE"],
        industry: "Female Tech Empowerment + Fintech",
        website: "https://linktr.ee/Herconomy",
      },
      {
        companyName: "hytchafrica",
        companyTwitterHandle: "hytchafrica",
        foundersTwitterHandle: ["thislaolu"],
        industry: "Shared commuting.",
        website: "https://hytch.africa",
      },
    ],
  },
  {
    name: "i",
    company: [
      {
        companyName: "ifluxdotapp",
        companyTwitterHandle: "ifluxdotapp",
        foundersTwitterHandle: ["ifluxdotapp"],
        industry: "Payment infrastructure",
        website: "https://iflux.app",
      },
    ],
  },
  {
    name: "j",
    company: [
      {
        companyName: "JastTech",
        companyTwitterHandle: "JastTech",
        foundersTwitterHandle: ["CoucoSeth"],
        industry: "Mobile and Web apps service provider",
        website: "https://www.jastTech.com",
      },
      {
        companyName: "Jiggyvest",
        companyTwitterHandle: "Jiggyvest",
        foundersTwitterHandle: ["hachi"],
        industry: "JiggyTech",
        website: "https://www.jiggyvest.com",
      },
    ],
  },
  {
    name: "k",
    company: [
      {
        companyName: "Kashbase",
        companyTwitterHandle: "Kashbase",
        foundersTwitterHandle: ["TheMideOlayinka"],
        industry: "Savings infrastructure",
        website: "https://kashbase.com",
      },
      {
        companyName: "Kobo360",
        companyTwitterHandle: "Kobo360",
        foundersTwitterHandle: ["ObiOzor", "IfeOyedeleII"],
        industry: "Logistics",
        website: "https://www.kobo360.com",
      },
      {
        companyName: "Kudabank",
        companyTwitterHandle: "Kudabank",
        foundersTwitterHandle: ["Babsogundeyi"],
        industry: "Fintech",
        website: "https://kudabank.com",
      },
      {
        companyName: "Kudi",
        companyTwitterHandle: "Kudi",
        foundersTwitterHandle: ["waleyinks"],
        industry: "Agency Banking/Digital banking",
        website: "https://kudi.com/marketplace",
      },
      {
        companyName: "Kudibar",
        companyTwitterHandle: "Kudibar",
        foundersTwitterHandle: ["codebasher_"],
        industry: "Event ticketing platform",
        website: "https://kudibar.com",
      },
      {
        companyName: "Kudisms",
        companyTwitterHandle: "Kudisms",
        foundersTwitterHandle: ["MeduguOS"],
        industry: "Mobile Communication",
        website: "https://kudisms.net",
      },
      {
        companyName: "Kwik",
        companyTwitterHandle: "Kwik",
        foundersTwitterHandle: ["RomainPoirot-lellig"],
        industry: "Logistics",
        website: "https://kwik.delivery",
      },
    ],
  },
  {
    name: "l",
    company: [
      {
        companyName: "LemonadeFinance",
        companyTwitterHandle: "LemonadeFinance",
        foundersTwitterHandle: ["ridwan_olalere"],
        industry: "FinTech",
        website: "https://www.lemonade.finance",
      },
    ],
  },
  {
    name: "m",
    company: [
      {
        companyName: "myclassroomng",
        companyTwitterHandle: "myclassroomng",
        foundersTwitterHandle: ["isholabaryor"],
        industry: "Tech Education",
        website: "",
      },
      {
        companyName: "MytruQ",
        companyTwitterHandle: "MytruQ",
        foundersTwitterHandle: ["WilliamsFatayo"],
        industry: "Logistics",
        website: "https://mytruq.com",
      },
    ],
  },
  {
    name: "n",
    company: [
      {
        companyName: "Neviwi",
        companyTwitterHandle: "Neviwi",
        foundersTwitterHandle: ["OnyimeStan", "Chinemife"],
        industry: "Ecommerce",
        website: "https://neviwi.com",
      },

      {
        companyName: "nguvuhealth",
        companyTwitterHandle: "nguvuhealth",
        foundersTwitterHandle: ["jfkoya"],
        industry: "Healthtech",
        website: "https://www.nguvuhealth.com",
      },
    ],
  },
  {
    name: "o",
    company: [
      {
        companyName: "offmychest_app",
        companyTwitterHandle: "offmychest_app",
        foundersTwitterHandle: ["davidobidu", "Mercee__"],
        industry: "Healthcare & Social Networking",
        website: "https://omcmobile.app",
      },
      {
        companyName: "onlinehubng",
        companyTwitterHandle: "onlinehubng",
        foundersTwitterHandle: ["isholabaryor"],
        industry: "Tech Education",
        website: "https://onlinehubng.com",
      },
      {
        companyName: "Opay",
        companyTwitterHandle: "opay",
        foundersTwitterHandle: ["Favourori_"],
        industry: "Financial technology infrastructure",
        website: "https://opay.com",
      },
      {
        companyName: "ourpaydayHQ",
        companyTwitterHandle: "ourpaydayHQ",
        foundersTwitterHandle: ["Favourori_"],
        industry: "Financial technology infrastructure",
        website: "https://usepayday.com",
      },
      {
        companyName: "OurPassCo",
        companyTwitterHandle: "OurPassCo",
        foundersTwitterHandle: ["Mzter_sam"],
        industry: "Payment infrastructure",
        website: "https://www.ourpass.co",
      },
    ],
  },
  {
    name: "p",
    company: [
      {
        companyName: "Patricia",
        companyTwitterHandle: "Patricia",
        foundersTwitterHandle: ["Fejizzy"],
        industry: "FinTech",
        website: "https://www.mypatricia.co",
      },
      {
        companyName: "payercoins",
        companyTwitterHandle: "payercoins",
        foundersTwitterHandle: ["AdeleyeVictor_"],
        industry: "Crypto Payment Infrastructure/Web3",
        website: "https://www.payercoins.com",
      },
      {
        companyName: "PayPeckerHQ",
        companyTwitterHandle: "PayPeckerHQ",
        foundersTwitterHandle: ["docolumide"],
        industry: "E-commerce",
        website: "https://paypecker.co",
      },
      {
        companyName: "Paystack",
        companyTwitterHandle: "paystack",
        foundersTwitterHandle: ["shollsman", "0x"],
        industry: "Payment infrastructure",
        website: "https://paystack.com",
      },
      {
        companyName: "Pickmeupservice",
        companyTwitterHandle: "Pickmeupservice",
        foundersTwitterHandle: ["SkimaSax", "AdewaleOretuga"],
        industry: "Logistics",
        website: "",
      },
    ],
  },
  {
    name: "q",
    company: [
      {
        companyName: "QuabblyHQ",
        companyTwitterHandle: "QuabblyHQ",
        foundersTwitterHandle: ["theernestdavid", "jamzig1"],
        industry: "Automation, No-Code",
        website: "https://quabbly.com",
      },
    ],
  },
  {
    name: "r",
    company: [
      {
        companyName: "ReelFruit",
        companyTwitterHandle: "ReelFruit",
        foundersTwitterHandle: ["AffiSupaStar"],
        industry: "AgroTech",
        website: "https://reelfruit.com",
      },
      {
        companyName: "Risevest",
        companyTwitterHandle: "Risevest",
        foundersTwitterHandle: ["eldivyn"],
        industry: "Digital Wealth (Fintech)",
        website: "https://rise.capital",
      },
      {
        companyName: "Rosehood Technology Risk Consulting Group",
        companyTwitterHandle: "Rosehood Technology Risk Consulting Group",
        foundersTwitterHandle: ["mikerosy", "RosyRomike"],
        industry: "Technology Risk & Consulting",
        website: "http://Techrisk.co.ke",
      },
    ],
  },
  {
    name: "s",
    company: [
      {
        companyName: "safeboda",
        companyTwitterHandle: "safeboda",
        foundersTwitterHandle: ["Babajiide"],
        industry: "Transportation",
        website: "https://safeboda.com/ug",
      },
      {
        companyName: "shecluded",
        companyTwitterHandle: "shecluded",
        foundersTwitterHandle: ["ifyhopee"],
        industry: "Fintech + Female Tech Empowerment",
        website: "https://shecluded.com",
      },
      {
        companyName: "smartretailNG",
        companyTwitterHandle: "smartretailNG",
        foundersTwitterHandle: ["Ade_lekannnn"],
        industry: "Retail & commerce",
        website: "https://twitter.com/smartretailng",
      },
      {
        companyName: "SoochNigeria",
        companyTwitterHandle: "SoochNigeria",
        foundersTwitterHandle: ["jay_can_do"],
        industry: "Beverage/Food Processing",
        website: "https://m.facebook.com/soochnigeria",
      },
      {
        companyName: "spatialnodehq",
        companyTwitterHandle: "spatialnodehq",
        foundersTwitterHandle: ["jeafreezy"],
        industry:
          "Professional Networking, community, Social Media (micro blogging)",
        website: "https://spatialnode.net/home",
      },
      {
        companyName: "SpireAfrica",
        companyTwitterHandle: "SpireAfrica",
        foundersTwitterHandle: ["madebycharles"],
        industry: "Customer Experience (feedback)",
        website: "https://www.spire.africa",
      },
      {
        companyName: "SwiftFinanceApp",
        companyTwitterHandle: "SwiftFinanceApp",
        foundersTwitterHandle: ["dammieololade", "adeileri", "Anani_oluwatobi"],
        industry: "SME Banking",
        website: "https://www.swiftfinance.app",
      },
    ],
  },
  {
    name: "t",
    company: [
      {
        companyName: "TalentQL",
        companyTwitterHandle: "TalentQL",
        foundersTwitterHandle: ["AdewaleYusuf_", "hackSultan"],
        industry: "Tech Recruitment",
        website: "https://talentql.com",
      },
      {
        companyName: "Tech4DevHQ",
        companyTwitterHandle: "Tech4DevHQ",
        foundersTwitterHandle: ["diwuraoladepo", "JoelOgunsola"],
        industry: "Tech NGO",
        website: "https://linktr.ee/tech4dev",
      },
      {
        companyName: "TerragonGroup",
        companyTwitterHandle: "TerragonGroup",
        foundersTwitterHandle: ["Eloumeh"],
        industry: "Data and Marketing technology",
        website: "https://terragongroup.com",
      },
      {
        companyName: "themoneyafrica",
        companyTwitterHandle: "themoneyafrica",
        foundersTwitterHandle: ["tosinolaseinde"],
        industry: "Tech Education",
        website: "https://themoneyafrica.com",
      },
      {
        companyName: "Timely Advisory",
        companyTwitterHandle: "Timely Advisory",
        foundersTwitterHandle: ["ehindola", "oladapoyusuf"],
        industry: "Legal and finance advisory",
        website: "",
      },
      {
        companyName: "ToffeeTribe",
        companyTwitterHandle: "ToffeeTribe",
        foundersTwitterHandle: ["NgindaNganga", "KarambuMathai"],
        industry: "Remote Work Directory",
        website: "https://www.toffeetribe.com",
      },
      {
        companyName: "tradeDepotHQ",
        companyTwitterHandle: "tradeDepotHQ",
        foundersTwitterHandle: ["kachizukanne"],
        industry: "Retail",
        website: "https://www.tradedepot.co",
      },
      {
        companyName: "TreepzHQ",
        companyTwitterHandle: "TreepzHQ",
        foundersTwitterHandle: [
          "onyekaakumah",
          "johnnyena",
          "darkshayy",
          "john_shaibu",
        ],
        industry: "Shared Mobility",
        website: "https://linktr.ee/PlentyWaka",
      },
    ],
  },
  {
    name: "u",
    company: [
      {
        companyName: "uLessonApp",
        companyTwitterHandle: "uLessonApp",
        foundersTwitterHandle: ["SimShagaya"],
        industry: "Tech Education",
        website: "https://ulesson.com",
      },
      {
        companyName: "unboxdgifts",
        companyTwitterHandle: "unboxdgifts",
        foundersTwitterHandle: ["mrtoluadesina"],
        industry: "FinTech",
        website: "https://www.unboxd.gifts",
      },
      {
        companyName: "UrBizEdge",
        companyTwitterHandle: "UrBizEdge",
        foundersTwitterHandle: ["MichealOlafusi"],
        industry: "Tech Education",
        website: "https://www.urbizedge.com",
      },
    ],
  },
  { name: "v", companies: [] },
  {
    name: "w",
    company: [
      {
        companyName: "weare54gene",
        companyTwitterHandle: "weare54gene",
        foundersTwitterHandle: ["AbasiEneobong"],
        industry: "Health Tech",
        website: "https://54gene.com",
      },
      {
        companyName: "WellaHealth",
        companyTwitterHandle: "WellaHealth",
        foundersTwitterHandle: ["docneto"],
        industry: "Health Tech",
        website: "https://www.wellahealth.com",
      },
    ],
  },
  {
    name: "x",
    company: [
      {
        companyName: "xendfinance",
        companyTwitterHandle: "xendfinance",
        foundersTwitterHandle: ["AronuUgochukwu"],
        industry: "DeFi",
        website: "https://xend.finance",
      },
    ],
  },
  {
    name: "y",
    company: [
      {
        companyName: "yourflexapp",
        companyTwitterHandle: "yourflexapp",
        foundersTwitterHandle: ["realsisititi", "ekojournalist"],
        industry: "FunTech",
        website: "https://flex.com.ng",
      },
    ],
  },
  { name: "z", companies: [] },
];
