export default {
  startsWith: "g",
  companies: [
    {
      companyName: "Geotopup",
      companyTwitterHandle: "Geotopup",
      foundersTwitterHandle: ["ejilolahmed"],
      industry: "Fintech",
      website: "https://geotopup.com",
    },
    {
      companyName: "Gokada",
      companyTwitterHandle: "gokada_ng",
      foundersTwitterHandle: ["fahad792"],
      industry: "Transportation",
      website: "https://gokada.ng",
    },
    {
      companyName: "Gebeya",
      companyTwitterHandle: "GebeyaTalent",
      foundersTwitterHandle: ["amahinduka"],
      industry: "Tech Talent Marketplace",
      website: "https://gebeya.com",
    },
    {
      companyName: "GetEquity",
      companyTwitterHandle: "getequity",
      foundersTwitterHandle: ["bigbrutha_", "WilliamOkafor"],
      industry: "Startup Financing",
      website: "https://www.getequity.io",
    },
    {
      companyName: "Gona",
      companyTwitterHandle: "GonaJudy",
      foundersTwitterHandle: ["gona_judy"],
      industry: "Agritech",
      website: "https://sttakenya.org/",
    },
    {
      companyName: "Grazac",
      companyTwitterHandle: "grazacng",
      foundersTwitterHandle: ["AdeleyeVictor_"],
      industry: "Tech Education",
      website: "https://www.grazac.com.ng",
    },
    {
      companyName: "Grey",
      companyTwitterHandle: "Grey",
      foundersTwitterHandle: ["femicodes", "kingidee"],
      industry: "FinTech",
      website: "https://grey.co",
    },
    {
      companyName: "Gata",
      companyTwitterHandle: "gatatransport",
      foundersTwitterHandle: ["GataHarrison"],
      industry: "Transportation",
      website: "https://gatatransport.com.ng",
    },
  ],
};
