export default {
  startsWith: "k",
  companies: [
    {
      companyName: "Kashbase",
      companyTwitterHandle: "Kashbase",
      foundersTwitterHandle: ["TheMideOlayinka"],
      industry: "Savings infrastructure",
      website: "https://kashbase.com",
    },
    {
      companyName: "Kloud Commerce",
      companyTwitterHandle: "KloudCommerceHQ",
      foundersTwitterHandle: ["docolumide"],
      industry: "E-commerce",
      website: "https://www.kloudcommerce.co/",
    },
    {
      companyName: "Kobo360",
      companyTwitterHandle: "Kobo360",
      foundersTwitterHandle: ["ObiOzor", "IfeOyedeleII"],
      industry: "Logistics",
      website: "https://www.kobo360.com",
    },
    {
      companyName: "Kuda Bank",
      companyTwitterHandle: "Kudabank",
      foundersTwitterHandle: ["Babsogundeyi"],
      industry: "Fintech",
      website: "https://kuda.com",
    },
    {
      companyName: "Kudi",
      companyTwitterHandle: "Kudi",
      foundersTwitterHandle: ["waleyinks"],
      industry: "Agency Banking/Digital banking",
      website: "https://kudi.com/marketplace",
    },
    {
      companyName: "Kudibar",
      companyTwitterHandle: "Kudibar",
      foundersTwitterHandle: ["codebasher_"],
      industry: "Event ticketing platform",
      website: "https://kudibar.com",
    },
    {
      companyName: "Kudi SMS",
      companyTwitterHandle: "Kudisms",
      foundersTwitterHandle: ["MeduguOS"],
      industry: "Mobile Communication",
      website: "https://kudisms.net",
    },
    {
      companyName: "Kwik",
      companyTwitterHandle: "Kwik",
      foundersTwitterHandle: ["RomainPoirot-lellig"],
      industry: "Logistics",
      website: "https://kwik.delivery",
    },
    {
      companyName: "KITS Technologies",
      companyTwitterHandle: "KitsTech_",
      foundersTwitterHandle: ["KitsTech_"],
      industry: "Cyber Security solutions",
      website: ":https://kits.ng/",
    },
  ],
};
