export default {
  startsWith: "l",
  companies: [
    {
      companyName: "LakexIO Technologies",
      companyTwitterHandle: "lakex_io",
      foundersTwitterHandle: ["o_o_lekan"],
      industry: "Tech Agency",
      website: "",
    },
    {
      companyName: "Lemonade Finance",
      companyTwitterHandle: "LemonadeFinance",
      foundersTwitterHandle: ["ridwan_olalere"],
      industry: "FinTech",
      website: "https://www.lemonade.finance",
    },
    {
      companyName: "LakexIO Technologies",
      companyTwitterHandle: "lakex_io",
      foundersTwitterHandle: ["o_o_lekan"],
      industry: "Tech Agency",
      website: "[] ",
    },
    {
      companyName: "Lori Systems",
      companyTwitterHandle: "LoriSystems",
      foundersTwitterHandle: [],
      industry: "Logistics/Tech",
      website: "https://www.lorisystems.com",
    },
    {
      companyName: "Lidya",
      companyTwitterHandle: "Lidya_Finance",
      foundersTwitterHandle: [],
      industry: "Credit Infrastructure(Fintech)",
      website: "https://www.lidya.info/",
    },
    {
      companyName: "Lightech-I.T Firm",
      companyTwitterHandle: "Lightech_ITFirm",
      foundersLinkedin: "https://www.linkedin.com/in/noble-amaechi-63b13986" ,
      industry: "UI/Ux & Product Design ",
      website: "https://www.lightech.com.ng/",
    },
    {
      companyName: "Lihon Energy",
      companyTwitterHandle: "",
      foundersTwitterHandle: "" ,
      industry: "Energy Tech",
      website: "https://lihonenergy.com",
    },
    {
      companyName: "Lipa Later",
      companyTwitterHandle: "lipalaterke",
      foundersTwitterHandle: "CaptainMuli",
      industry: "FinTech",
      website: "https://lipalater.com/",
    },
  ],
};