export default {
  startsWith: "p",
  companies: [
    {
      companyName: "Paystack",
      companyTwitterHandle: "paystack",
      foundersTwitterHandle: ["shollsman", "0x"],
      industry: "Payment infrastructure",
      website: "https://paystack.com",
    },
    {
      companyName: "paga",
      companyTwitterHandle: "paga",
      foundersTwitterHandle: ["oviosu"],
      industry: "Financial Technology (Fintech)",
      website: "https://www.mypaga.com/",
    },
    {
      companyName: "Pawame",
      companyTwitterHandle: "PawameAfrica",
      foundersTwitterHandle: ["MajdChaaya"],
      industry: "Energy Transformation",
      website: "https://pawame.com",
    },
    {
      companyName: "Pocket by Piggyvest",
      companyTwitterHandle: "@getpocketapp",
      foundersTwitterHandle: ["@OdunEweniyi"],
      industry: "FinTech",
      website: "https://pocketapp.com/",
    },
    {
      companyName: "P2Vest",
      companyTwitterHandle: "p2vest",
      foundersTwitterHandle: [ ],
      industry: "Fintech",
      website: "https://www.p2vest.com",
    },
    {
      companyName: "Piggyvest",
      companyTwitterHandle: "@piggyBankNG",
      foundersTwitterHandle: ["@OdunEweniyi"],
      industry: "FinTech",
      website: "https://www.piggyvest.com/",
    },
    {
      companyName: "Patricia",
      companyTwitterHandle: "Patricia",
      foundersTwitterHandle: ["Fejizzy"],
      industry: "FinTech",
      website: "https://www.mypatricia.co",
    },
    {
      companyName: "Payercoins",
      companyTwitterHandle: "payercoins",
      foundersTwitterHandle: ["AdeleyeVictor_"],
      industry: "Crypto Payment Infrastructure/Web3",
      website: "https://www.payercoins.com",
    },
    {
      companyName: "Paystack",
      companyTwitterHandle: "paystack",
      foundersTwitterHandle: ["shollsman", "0x"],
      industry: "Payment infrastructure",
      website: "https://paystack.com",
    },
    {
      companyName: "Pick me up service",
      companyTwitterHandle: "Pickmeupservice",
      foundersTwitterHandle: ["SkimaSax", "AdewaleOretuga"],
      industry: "Logistics",
      website: "http://pickmeup.com.ng",
    },
    {
      companyName: "pesapal",
      companyTwitterHandle: "Pesapal",
      foundersTwitterHandle: ["AgostaL"],
      industry: "Payment infrastructure",
      website: "http://pesapal.com",
    },
    {
      companyName: "patricia",
      companyTwitterHandle: "patriciaswitch",
      foundersTwitterHandle: ["fejizzy"],
      industry: "E-commerce company",
      website: "http://www.mypatricia.com",
    },
    {
      companyName: "patricia",
      companyTwitterHandle: "patriciaswitch",
      foundersTwitterHandle: ["fejizzy"],
      industry: "E-commerce company",
      website: "http://www.mypatricia.com",
    },
    {
      companyName: "palmpay",
      companyTwitterHandle: ["palmpay_ng ","palmpaygh"],
      industry: "Fin-Tech",
      website: "http://www.palmpay.com",
    },
    {
      companyName: "PAL",
      companyTwitterHandle: [],
      industry: "Fin-Tech",
      website: "https://www.pals.africa/",
    },
    {
      companyName: "Prunedge",
      companyTwitterHandle: "Prunedge",
      foundersTwitterHandle: ["JoelOgunsola"],
      industry: "Tech agency",
      website: "https://prunedge.com",
    },
  ],
};
