export default {
  startsWith: "s",
  companies: [
    {
      companyName: "safeboda",
      companyTwitterHandle: "safeboda",
      foundersTwitterHandle: ["Babajiide"],
      industry: "Transportation",
      website: "https://safeboda.com/ug",
    },
    {
      companyName: "Safe House",
      companyTwitterHandle: "buysafehouse",
      foundersTwitterHandle: ["SeunKOlajide"],
      industry: "Real Estate",
      website: "https://www.buysafehouse.com",
    },
    {
      companyName: "Sembuse",
      companyTwitterHandle: "@sembuse.com",
      foundersTwitterHandle: ["Timothy mbugua"],
      industry: "social network",
      website: "https://Sembuse.com",
    },
    {
      companyName: "Sequoon",
      companyTwitterHandle: "sequoon",
      foundersTwitterHandle: ["Omar ElDessouky", "Mohamed ElKhatjeb"],
      industry: "proptech",
      website: "https://https://www.sequoon.com",
    },
    {
      companyName: "Shecluded",
      companyTwitterHandle: "shecluded",
      foundersTwitterHandle: ["ifyhopee"],
      industry: "Fintech + Female Tech Empowerment",
      website: "https://shecluded.com",
    },
    {
      companyName: "Smartretail",
      companyTwitterHandle: "smartretailNG",
      foundersTwitterHandle: ["Ade_lekannnn"],
      industry: "Retail & commerce",
      website: "https://twitter.com/smartretailng",
    },
    {
      companyName: "Sooch Nigeria",
      companyTwitterHandle: "SoochNigeria",
      foundersTwitterHandle: ["jay_can_do"],
      industry: "Beverage/Food Processing",
      website: "https://m.facebook.com/soochnigeria",
    },
    {
      companyName: "Spatialnode",
      companyTwitterHandle: "spatialnodehq",
      foundersTwitterHandle: ["jeafreezy"],
      industry:
        "Professional Networking, community, Social Media (micro blogging)",
      website: "https://spatialnode.net/home",
    },
    {
      companyName: "Spire Africa",
      companyTwitterHandle: "SpireAfrica",
      foundersTwitterHandle: ["madebycharles"],
      industry: "Customer Experience (feedback)",
      website: "https://www.getspire.io/",
    },
    {
      companyName: "SunFi",
      companyTwitterHandle: "sunfi_hq",
      foundersTwitterHandle: ["thomas_rotimi"],
      industry: "Fintech, Energy",
      website: "https://www.sunfi.co/",
    },
    {
      companyName: "Swift Finance",
      companyTwitterHandle: "SwiftFinanceApp",
      foundersTwitterHandle: ["dammieololade", "adeileri", "Anani_oluwatobi"],
      industry: "SME Banking",
      website: "https://www.swiftfinance.app",
    },
    {
      companyName: "Stickerkeen",
      companyTwitterHandle: "stickerkeen",
      foundersTwitterHandle: ["saintmalik_"],
      industry: "Promotional Product Management",
      website: "https://stickerkeen.com",
    },
  ],
};
