export default {
  startsWith: "t",
  companies: [
    {
      companyName: "TalentQL",
      companyTwitterHandle: "TalentQL",
      foundersTwitterHandle: ["AdewaleYusuf_", "hackSultan"],
      industry: "Tech Recruitment",
      website: "https://talentql.com",
    },
    {
      companyName: "Tech4Dev",
      companyTwitterHandle: "Tech4DevHQ",
      foundersTwitterHandle: ["diwuraoladepo", "JoelOgunsola"],
      industry: "Tech NGO",
      website: "https://linktr.ee/tech4dev",
    },
    {
      companyName: "Terragon Group",
      companyTwitterHandle: "TerragonGroup",
      foundersTwitterHandle: ["Eloumeh"],
      industry: "Data and Marketing technology",
      website: "https://terragongroup.com",
    },
    {
      companyName: "The Money Africa",
      companyTwitterHandle: "themoneyafrica",
      foundersTwitterHandle: ["tosinolaseinde"],
      industry: "Tech Education",
      website: "https://themoneyafrica.com",
    },
    {
      companyName: "Timely Advisory",
      companyTwitterHandle: "Timely Advisory",
      foundersTwitterHandle: ["ehindola", "oladapoyusuf"],
      industry: "Legal and finance advisory",
      website: "",
    },
    {
      companyName: "ToffeeTribe",
      companyTwitterHandle: "ToffeeTribe",
      foundersTwitterHandle: ["NgindaNganga", "KarambuMathai"],
      industry: "Remote Work Directory",
      website: "https://www.toffeetribe.com",
    },
    {
      companyName: "Trade Depot",
      companyTwitterHandle: "tradeDepotHQ",
      foundersTwitterHandle: ["kachizukanne"],
      industry: "Retail",
      website: "https://www.tradedepot.co",
    },
    {
      companyName: "Treepz",
      companyTwitterHandle: "TreepzHQ",
      foundersTwitterHandle: [
        "onyekaakumah",
        "johnnyena",
        "darkshayy",
        "john_shaibu",
      ],
      industry: "Shared Mobility",
      website: "https://linktr.ee/PlentyWaka",
    },
    {
      companyName: "TruQ",
      companyTwitterHandle: "MytruQ",
      foundersTwitterHandle: ["WilliamsFatayo"],
      industry: "Logistics",
      website: "https://mytruq.com",
    },
    {
      companyName: "Tech cabal",
      companyTwitterHandle: "Techcabal",
      foundersTwitterHandle: ["Obaolarewaju"],
      industry: "Tech media/research ",
      website: "https://techcabal.com",
    },
    {
      companyName: "Jumia Travel",
      companyTwitterHandle: "jumia_travel",
      foundersTwitterHandle: ["sachapoignonnec", "raphaelapter"],
      industry: "Travel",
      website: "https://travel.jumia.com",
    },
    {
      companyName: "Jumia Deals",
      companyTwitterHandle: "jumia_Group",
      foundersTwitterHandle: ["samchappatte", "sachapoignonnec"],
      industry: "Deals",
      website: "https://deals.jumia.com",
    },
    {
      companyName: "Trove",
      companyTwitterHandle: "trovefinance",
      foundersTwitterHandle: ["tomisuave"],
      industry: "Digital Wealth (Fintech)",
      website: "https://www.troveapp.co",
    },
    {
      companyName: "TOG Africa",
      companyTwitterHandle: "TogAfrica",
      foundersTwitterHandle: [""],
      industry: "Software Development",
      website: "https://www.togafrica.com",
    },
  ],
};
