export default {
  startsWith: "v",
  companies: [
    {
      companyName: "Vantagepay",
      companyTwitterHandle: "VantagepayA",
      foundersTwitterHandle: ["VantagepayA"],
      industry: "FinTech",
      website: "https://vantagepay.com",
    },
    {
      companyName: "Veenode Technologies",
      companyTwitterHandle: "Veenode",
      foundersTwitterHandle: ["VictorAkinode"],
      industry: "Branding/Consulation",
      website: "https://veenodetech.com/",
    },
    {
      companyName: "Vendease",
      companyTwitterHandle: "VendeaseAfrica",
      foundersTwitterHandle: ["tundde"],
      industry: "Agro-Tech",
      website: "https://vendease.com",
    },
    {
      companyName: "VerifyMe",
      companyTwitterHandle: "VMNigeria",
      foundersTwitterHandle: ["OlutunjiOluwole"],
      industry: "FinTech/Digital Economy",
      website: "https://www.verifyme.ng",
    },
    {
      companyName: "VBank",
      companyTwitterHandle: "vbankng",
      foundersTwitterHandle: ["Haruna Dalhatu Iya"],
      Industry: "Fintech",
      website: "https://www.vbank.com",
    },
    {
      companyName: "vodacom",
      companyTwitterHandle: "Vodacom",
      foundersTwitterHandle: ["shameeljoosub"],
      industry: "Digital/Financial Services",
      website: "https://www.vodacom.co.za",
    },
    { 
      companyName: "Voguepay", 
      companyTwitterHandle: "Voguepay", 
      foundersTwitterHandle: ["ibromomo"], 
      industry: "Fintech", 
      website: "https://www.voguepay.com", 
    },
    {
      companyName: "VeendHQ",
      companyTwitterHandle: "VeendHQ",
      foundersTwitterHandle: ["iolufemitalks"],
      industry: "Fintech",
      website: "https://veendhq.com/",
    },
    {
      companyName: "Valr",
      companyTwitterHandle: "VALRdotcom",
      foundersTwitterHandle: ["farzamehsani"],
      industry: "Fintech",
      website: "https://www.valr.com/",
    },
    {
      companyName: "VC4a",
      companyTwitterHandle: "Vc4Africa",
      foundersTwitterHandle: ["zia505"],
      industry: "Venture capital",
      website: "https://vc4a.com",
    },
  ],
};
