export default {
  startsWith: "z",
  companies: [
    {
      companyName: "Zipline",
      companyTwitterHandle: "@zipline",
      foundersTwitterHandle: ["Keller Rinaudo"],
      industry: "logistics",
      website: "https://flyzipline.com",
    },
    {
      companyName: "zando",
      companyTwitterHandle: "zando_co_za",
      foundersTwitterHandle: ["drgrantwbrown"],
      industry: "E-commerce",
      website: "https://www.zando.co.za",
    },
    {
      companyName: "ZirooPay",
      companyTwitterHandle: "@ZirooPay",
      foundersTwitterHandle: ["omoniyiolawale", "oluwaniisola"],
      industry: "Fintech",
      website: "https://ziroopay.com",
    },
    {
      companyName: "zeepay",
      companyTwitterHandle: "myzeepay",
      foundersTwitterHandle: ["andrewretail"],
      industry: "Fintech",
      website: "https://myzeepay.com",
    },
    {
      companyName: "zeddpay",
      companyTwitterHandle: "zeddpay",
      foundersTwitterHandle: ["pleasant0x", "olamidettw"],
      industry: "Fintech",
      website: "https://https://www.zeddpay.com",
    },
    {
      companyName: "Zumi",
      companyTwitterHandle: "-",
      foundersTwitterHandle: ["Sabrina Dorman", "William McCarren"],
      industry: "e-commerce",
      website: "https://www.zumi.co.ke/",
    },
    {
      companyName: "Zanifu",
      companyTwitterHandle: "ZanifuLtd",
      foundersLinkedInHandle: ["Steve Biko", "Sebastian Mithika"],
      industry: "fintech",
      website: "https://www.zanifu.com/",
    },
    {
      companyName: "Zuri Health",
      companyTwitterHandle: "ZuriHealth",
      foundersLinkedInHandle: ["IkechukwuAnoke"],
      industry: "healthtech",
      website: "https://nigeria.zuri.health/",
    },
  ],
};
